# Generated by Django 5.0.6 on 2024-08-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_rename_side_effects_medicine_sideeffects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
        migrations.RenameModel(
            old_name='Ingredient',
            new_name='Ingredients',
        ),
        migrations.RenameModel(
            old_name='Medicine',
            new_name='Medicines',
        ),
        migrations.RenameModel(
            old_name='SideEffect',
            new_name='SideEffects',
        ),
    ]
