# Generated by Django 5.1 on 2024-08-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_rename_category_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='expiration_date',
            field=models.DateField(help_text='Expiration date of the medicine', verbose_name='Expiration Date'),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='Manufacturer of the medicine', max_length=255, verbose_name='Manufacturer'),
        ),
    ]
