# Generated by Django 5.1 on 2024-09-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_alter_medicines_expiration_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Test Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Test Description')),
                ('test_cost', models.FloatField(verbose_name='Test cost')),
            ],
        ),
    ]
