# Generated by Django 5.1.4 on 2024-12-10 10:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_labtests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicines',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='medicines',
            name='stock',
        ),
        migrations.CreateModel(
            name='MedicineStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(help_text='Stock quantity of the medicine', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock')),
                ('expiration_date', models.DateField(help_text='Expiration date of the medicine', verbose_name='Expiration Date')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Medicine_Stock', to='pharmacy.medicines', verbose_name='Medicine Details')),
            ],
        ),
    ]
