# Generated by Django 5.1.4 on 2024-12-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_remove_medicines_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='allergies',
            field=models.ManyToManyField(help_text='Patients with these allergies should avoid.', related_name='medicines', to='pharmacy.allergies', verbose_name='Allergies'),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='categories',
            field=models.ManyToManyField(help_text='Categories of the medicine', related_name='medicines', to='pharmacy.categories', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='ingredients',
            field=models.ManyToManyField(help_text='Ingredients in the medicine', related_name='medicines', to='pharmacy.ingredients', verbose_name='Ingredients'),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='sideEffects',
            field=models.ManyToManyField(help_text='Possible side effects of the medicine', related_name='medicines', to='pharmacy.sideeffects', verbose_name='Side Effects'),
        ),
    ]
