# Generated by Django 5.1.4 on 2024-12-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_alter_medicines_allergies_alter_medicines_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Allergy for the medicines', max_length=255, verbose_name='Allergens')),
            ],
        ),
        migrations.RemoveField(
            model_name='medicines',
            name='allergies',
        ),
        migrations.AddField(
            model_name='medicines',
            name='allergens',
            field=models.ManyToManyField(help_text='Patients with these allergies should avoid.', related_name='medicines', to='pharmacy.allergens', verbose_name='Allergens'),
        ),
        migrations.DeleteModel(
            name='Allergies',
        ),
    ]
