# Generated by Django 5.1.4 on 2024-12-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_allergens_remove_medicines_allergies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='manufacturer',
            field=models.CharField(help_text='Manufacturer of the medicine', max_length=255, verbose_name='Manufacturer'),
        ),
    ]
