# Generated by Django 5.0.3 on 2024-06-29 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoruser',
            name='registration_number',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
