# Generated by Django 5.1 on 2024-09-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_doctoruser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientuser',
            name='occupation',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
