# Generated by Django 5.1 on 2024-09-01 16:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_patientuser_occupation'),
        ('pharmacy', '0005_labtests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoruser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Doctor User Details'),
        ),
        migrations.AlterField(
            model_name='patientuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Patient User Details'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Appointment Date')),
                ('time_assigned', models.TimeField(verbose_name='Time Assigned')),
                ('reason_for_visit', models.TextField(blank=True, null=True, verbose_name='Reason for Visit')),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('No Show', 'No Show')], default='Scheduled', max_length=20, verbose_name='Status')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='doctor.doctoruser', verbose_name='Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctor.patientuser', verbose_name='Patient')),
            ],
        ),
        migrations.CreateModel(
            name='PrescribedLabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField(verbose_name='Test Date')),
                ('test_result', models.TextField(blank=True, null=True, verbose_name='Test Result')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20, verbose_name='Test Status')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='lab_tests/', verbose_name='Test Report')),
                ('labtest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescribed_lab_test', to='pharmacy.labtests', verbose_name='Lab Test')),
            ],
        ),
        migrations.CreateModel(
            name='PrescribedMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.PositiveIntegerField(help_text='Number of times the medicine should be taken per day', validators=[django.core.validators.MinValueValidator(1)])),
                ('timings', models.CharField(choices=[('before_food', 'before_food'), ('after_food', 'after_food'), ('custom', 'custom')], max_length=11, verbose_name='Timing')),
                ('customTiming', models.TimeField(blank=True, null=True)),
                ('duration_value', models.PositiveIntegerField(help_text='Duration value based on the selected unit', validators=[django.core.validators.MinValueValidator(1)])),
                ('duration_unit', models.CharField(choices=[('Days', 'Days'), ('Months', 'Months')], max_length=6, verbose_name='Duration Unit')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_medicine', to='pharmacy.medicines', verbose_name='Medicine Details')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='doctor.appointment', verbose_name='Appointment Details')),
                ('labtests', models.ManyToManyField(blank=True, related_name='prescription', to='doctor.prescribedlabtest', verbose_name='Prescribed Lab Tests')),
                ('medicines', models.ManyToManyField(blank=True, related_name='prescription', to='doctor.prescribedmedicine', verbose_name='Medicines Prescribed')),
            ],
        ),
        migrations.AddConstraint(
            model_name='prescribedmedicine',
            constraint=models.CheckConstraint(condition=models.Q(('frequency__gte', 1)), name='check_valid_frequency'),
        ),
        migrations.AddConstraint(
            model_name='prescribedmedicine',
            constraint=models.CheckConstraint(condition=models.Q(('duration_value__gte', 1)), name='check_valid_duration_value'),
        ),
    ]
