# Generated by Django 5.1.3 on 2024-11-26 11:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_alter_doctoruser_user_alter_patientuser_user_and_more'),
        ('pharmacy', '0005_labtests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescribedmedicine',
            name='duration_value',
            field=models.IntegerField(help_text='Duration value based on the selected unit', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='prescribedmedicine',
            name='frequency',
            field=models.IntegerField(help_text='Number of times the medicine should be taken per day', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='prescribedmedicine',
            name='medicine',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_medicine', to='pharmacy.medicines', verbose_name='Medicine Details'),
        ),
    ]
