# Generated by Django 5.1.4 on 2024-12-09 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_alter_prescribedmedicine_duration_value_and_more'),
        ('pharmacy', '0005_labtests'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecializationAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='prescribedmedicine',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_medicine', to='pharmacy.medicines', verbose_name='Medicine Details'),
        ),
    ]
