# Generated by Django 5.1.4 on 2024-12-10 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_specializationavailable_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoruser',
            name='specialization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doctor', to='doctor.specializationavailable', verbose_name='Specialization field for this doctor'),
        ),
        migrations.AlterField(
            model_name='doctoruser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='doctor', to=settings.AUTH_USER_MODEL, verbose_name='Doctor User Details'),
        ),
    ]
