# Generated by Django 5.1.4 on 2024-12-10 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_doctoruser_specialization_alter_doctoruser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoruser',
            name='experience',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)]),
        ),
    ]
