# Generated by Django 5.1.4 on 2024-12-10 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_alter_doctoruser_experience'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientuser',
            name='occupation',
        ),
        migrations.AddField(
            model_name='prescription',
            name='additonal_information',
            field=models.TextField(blank=True, help_text='Additional Information for the patient', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='digital_signature',
            field=models.ImageField(default=None, null=True, upload_to='signatures/', verbose_name='Digital Signature'),
        ),
        migrations.AlterField(
            model_name='patientuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='patient', to=settings.AUTH_USER_MODEL, verbose_name='Patient User Details'),
        ),
    ]
