# Generated by Django 5.1 on 2024-08-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Doctor', 'Doctor'), ('Pharmacy', 'Pharmacy'), ('FrontDesk', 'FrontDesk'), ('Patient', 'Patient')], max_length=9),
        ),
    ]
