# Generated by Django 5.1 on 2024-09-01 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='occupation',
        ),
    ]
