# Generated by Django 5.1.4 on 2024-12-09 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_remove_user_occupation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpecializationAvailable',
        ),
    ]
